nodeLinker: pnp

packageExtensions:
  eslint-config-react-app@*:
    dependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"
  react-dev-utils@*:
    dependencies:
      typescript: ^4.5.5
      webpack: ^5
  react-scripts@*:
    dependencies:
      autoprefixer: "*"
  webpack-dev-server@*:
    dependencies:
      "@types/express": "*"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
